criaCartao('assets/Versopergunta1.png', 'assets/01.png', 'assets/R1.png',  0)
criaCartao('assets/Versopergunta2.png', 'assets/02.png', 'assets/R2.png', 1)
criaCartao('assets/Versopergunta1.png', 'assets/03.png', 'assets/R3.png', 2)
criaCartao('assets/Versopergunta2.png', 'assets/04.png', 'assets/R4.png', 3)
criaCartao('assets/Versopergunta1.png', 'assets/05.png', 'assets/R5.png', 4)
criaCartao('assets/Versopergunta2.png', 'assets/06.png', 'assets/R6.png',5)
criaCartao('assets/Versopergunta1.png', 'assets/07.png', 'assets/R7.png',6)
criaCartao('assets/Versopergunta2.png', 'assets/08.png', 'assets/R8.png',7)
criaCartao('assets/Versopergunta1.png', 'assets/09.png', 'assets/R9.png',8)
criaCartao('assets/Versopergunta2.png', 'assets/10.png', 'assets/R10.png',9)
criaCartao('assets/Versopergunta1.png', 'assets/11.png', 'assets/R11.png',10)
criaCartao('assets/Versopergunta2.png', 'assets/12.png', 'assets/R12.png',11)
criaCartao('assets/Versopergunta1.png', 'assets/13.png', 'assets/R13.png',12)
criaCartao('assets/Versopergunta2.png', 'assets/14.png', 'assets/R14.png',13)
criaCartao('assets/Versopergunta1.png', 'assets/15.png', 'assets/R15.png',14)
criaCartao('assets/Versopergunta2.png', 'assets/16.png', 'assets/R16.png',15)
criaCartao('assets/Versopergunta1.png', 'assets/17.png', 'assets/R17.png',16)
criaCartao('assets/Versopergunta2.png', 'assets/18.png', 'assets/R18.png',17)
criaCartao('assets/Versopergunta1.png', 'assets/19.png', 'assets/R19.png',18)
criaCartao('assets/Versopergunta2.png', 'assets/20.png', 'assets/R20.png',19)
criaCartao('assets/Versopergunta1.png', 'assets/21.png', 'assets/R21.png',20)
criaCartao('assets/Versopergunta2.png', 'assets/22.png', 'assets/R22.png',21)
criaCartao('assets/Versopergunta1.png', 'assets/23.png', 'assets/R23.png',22)
criaCartao('assets/Versopergunta2.png', 'assets/24.png', 'assets/R24.png',23)
criaCartao('assets/Versopergunta1.png', 'assets/25.png', 'assets/R25.png',24)
